name: Run the code
on: workflow_dispatch
jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: reiichi001/PAC-Nag@9d2c2133b22eada3d8012050a2de58806afe3f0a # will this work?
        with:
          token: ${{secrets.TOKEN}}
          discord_webhook: ${{secrets.DISCORD_WEBHOOK_URL}}
          pacsheetslink: ${{secrets.PAC_SHEETS_LINK}}
