name: Run the code
on: workflow_dispatch
jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:
      - uses: ./ # Uses an action in the root directory
        with:
          node-version: 16
          token: ${{secrets.GITHUB_TOKEN}}
          discord_webhook: ${{secrets.DISCORD_WEBHOOK_URL}}
